### ISSUE TITLE
Arial Bold fonts not available

### ISSUE THREAD

**Issue by lordscarlet** [kublet/community#4]
```
src/main.cpp:84:39: error: 'Arial_20_Bold' was not declared in this scope
```

**Comment by audreylim** [comment]
Thanks, fixed in latest `kgfx` release. Please update the line in your `platformio.ini` file to:

```
 kublet/KGFX@^0.0.14
```

Then run `krate build` and see if it can find the font. If you see an `UnknownPackageError`, run `pio system prune`. You only need to prune cached data:

```
Prune cached data:
 - cached API requests
 - cached package downloads
 - temporary data
Do you want to continue? [y/N]: y
Space on disk: 5.52MB

Prune unnecessary core packages:
Calculating...
Do you want to continue? [y/N]: n
Aborted!
```

We made `kgfx` public on GitHub: https://github.com/kublet/kgfx and welcome contributions to it.
